#ifndef ADVANCEDOPERATIONS_GLOBAL_H
#define ADVANCEDOPERATIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADVANCEDOPERATIONS_LIBRARY)
#  define ADVANCEDOPERATIONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ADVANCEDOPERATIONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ADVANCEDOPERATIONS_GLOBAL_H
